<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.luowj.test.TestCaces" tests="3" time="0.008" ignored="1" failures="1" timestamp="05 三月 2019 06:42:03 GMT" skipped="0" hostname="TBN-0R3REM" errors="0">
  <testcase name="testdeme2" time="0.000" classname="com.luowj.test.TestCaces"/>
  <testcase name="testdemo1" time="0.008" classname="com.luowj.test.TestCaces">
    <failure type="java.lang.AssertionError" message="测试失败">
      <![CDATA[java.lang.AssertionError: 测试失败
	at org.testng.Assert.fail(Assert.java:94)
	at com.luowj.test.TestCaces.testdemo1(TestCaces.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.luowj.Application.main(Application.java:16)
]]>
    </failure>
  </testcase> <!-- testdemo1 -->
  <testcase name="testdeme3" time="0.000" classname="com.luowj.test.TestCaces"/>
  <testcase name="test" classname="com.luowj.test.TestCaces">
    <skipped/>
  </testcase> <!-- test -->
</testsuite> <!-- com.luowj.test.TestCaces -->
